# Generated by Django 4.2.2 on 2023-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=30)),
                ('soyadı', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'kategori',
            },
        ),
    ]
