# Generated by Django 4.2.2 on 2023-06-21 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloge', '0004_yorumlarmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YorumlarModel',
            new_name='YorumModel',
        ),
    ]
