# Generated by Django 4.2.2 on 2023-06-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0005_rename_yorumlarmodel_yorummodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('isim_soyisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişiml',
                'db_table': 'iletisim',
            },
        ),
    ]
