# Generated by Django 4.2.2 on 2023-06-21 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0006_iletisimmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisimmodel',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
