# Generated by Django 4.2.2 on 2023-06-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0007_iletisimmodel_olusturulma_tarihi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iletisimmodel',
            options={'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim'},
        ),
    ]
