# Generated by Django 4.2.2 on 2023-06-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0008_alter_iletisimmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='guncellenme_tarihi',
            new_name='duzenlenme_tarihi',
        ),
    ]
