# Generated by Django 4.2.2 on 2023-06-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0009_rename_guncellenme_tarihi_yorummodel_duzenlenme_tarihi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorimodel',
            options={'verbose_name': 'kategori', 'verbose_name_plural': 'kategoriler'},
        ),
        migrations.RenameField(
            model_name='yazilarmodel',
            old_name='kategori',
            new_name='kategoriler',
        ),
    ]
