# Generated by Django 4.2.2 on 2023-06-29 14:24

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0010_alter_kategorimodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorimodel',
            name='soyadı',
        ),
        migrations.AddField(
            model_name='kategorimodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='isim', unique=True),
            preserve_default=False,
        ),
    ]
