# Generated by Django 4.2.2 on 2023-06-29 14:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloge', '0012_remove_kategorimodel_slug_kategorimodel_soyadı'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorimodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='my-default-slug', editable=False, populate_from='isim', unique=True),
            preserve_default=False,
        ),
    ]
